// apps/playground-svelte/src/components/Section/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import type { SectionProps } from '../../types'

  const BADGE = {
    hook: 'hook option',
    playground: 'playground only'
  } as const

  let { title, origin, hint, children }: SectionProps = $props()
</script>

<details class={STYLES.section} data-pg="section" data-origin={origin} open>
  <summary class={STYLES.sectionTitle}>
    {title}
    <span class={STYLES.sectionBadge}>{BADGE[origin]}</span>
  </summary>
  <div class={STYLES.sectionBody}>
    {#if hint}
      <p class={STYLES.hint}>{hint}</p>
    {/if}
    {@render children()}
  </div>
</details>

// apps/playground-react/src/components/Section/index.tsx
import type { JSX } from 'react'
import { SectionProps } from '../../types'
import { STYLES } from '@swipi/playground-core'

const BADGE = {
  hook: 'hook option',
  playground: 'playground only'
}

const Section = ({
  title,
  origin,
  hint,
  children
}: SectionProps): JSX.Element => (
  <details
    className={STYLES.section}
    data-pg="section"
    data-origin={origin}
    open
  >
    <summary className={STYLES.sectionTitle}>
      {title}
      <span className={STYLES.sectionBadge}>{BADGE[origin]}</span>
    </summary>
    <div className={STYLES.sectionBody}>
      {hint && <p className={STYLES.hint}>{hint}</p>}
      {children}
    </div>
  </details>
)

export default Section
