// apps/playground-svelte/src/components/Toggle/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import type { ToggleProps } from '@swipi/playground-core'

  let {
    label,
    hint,
    checked,
    disabled = false,
    onChange
  }: ToggleProps = $props()

  const handleChange = (event: Event): void => {
    onChange((event.currentTarget as HTMLInputElement).checked)
  }
</script>

<label class={STYLES.toggle} data-pg="toggle">
  <input
    type="checkbox"
    class={STYLES.checkbox}
    {checked}
    {disabled}
    onchange={handleChange}
  />
  <span class={STYLES.toggleText}>
    <span class={STYLES.label} data-pg="label">{label}</span>
    {#if hint}
      <span class={STYLES.hint}>{hint}</span>
    {/if}
  </span>
</label>

// apps/playground-react/src/components/Toggle/index.tsx
import type { JSX } from 'react'
import { STYLES, ToggleProps } from '@swipi/playground-core'
import { useToggle } from './useToggle'

const Toggle = ({
  label,
  hint,
  checked,
  disabled = false,
  onChange
}: ToggleProps): JSX.Element => {
  const { handleChange } = useToggle({ onChange })

  return (
    <label className={STYLES.toggle} data-pg="toggle">
      <input
        type="checkbox"
        className={STYLES.checkbox}
        checked={checked}
        disabled={disabled}
        onChange={handleChange}
      />
      <span className={STYLES.toggleText}>
        <span className={STYLES.label} data-pg="label">
          {label}
        </span>
        {hint && <span className={STYLES.hint}>{hint}</span>}
      </span>
    </label>
  )
}

export default Toggle
