// apps/playground-react/src/components/CodeBlock/index.tsx
import type { JSX } from 'react'
import { useMemo } from 'react'
import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
import type { CodeBlockProps } from '@swipi/playground-core'

const CodeBlock = ({ code, language }: CodeBlockProps): JSX.Element => {
  const tokens = useMemo(() => highlight(code, language), [code, language])

  return (
    <pre className={STYLES.code}>
      {tokens.map((token, index) => (
        <span key={index} className={CODE_TOKEN_STYLES[token.kind]}>
          {token.text}
        </span>
      ))}
    </pre>
  )
}

export default CodeBlock

// apps/playground-vue/src/components/CodeBlock/index.vue
<template>
  <pre :class="STYLES.code"><span
      v-for="(token, index) in tokens"
      :key="index"
      :class="CODE_TOKEN_STYLES[token.kind]"
    >{{ token.text }}</span></pre>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
import type { CodeBlockProps } from '@swipi/playground-core'

const props = defineProps<CodeBlockProps>()

const tokens = computed(() => highlight(props.code, props.language))
</script>
