// packages/vue/scripts/consumer-app/src/Carousel.vue
<script setup>
import { computed } from 'vue'
import { useSwipiCarousel } from '@midstem/swipi-vue'

const SLIDES = ['one', 'two', 'three', 'four']

const SLIDE_WIDTH = 300

const [carouselRef, carousel] = useSwipiCarousel({ slideWidth: SLIDE_WIDTH })

const state = computed(
  () =>
    `${carousel.selectedIndex}/${carousel.snapCount}/${carousel.slidesCount}`
)
</script>

<template>
  <section>
    <div id="viewport" :ref="carouselRef">
      <div id="track">
        <article v-for="slide in SLIDES" :key="slide">{{ slide }}</article>
      </div>
    </div>

    <button id="next" @click="carousel.scrollNext()">next</button>

    <p id="state">{{ state }}</p>
  </section>
</template>

// packages/svelte/scripts/consumer-app/src/Carousel.svelte
<script>
  import { useSwipiCarousel } from '@midstem/swipi-svelte'

  const SLIDES = ['one', 'two', 'three', 'four']

  const SLIDE_WIDTH = 300

  const [carouselRef, carousel] = useSwipiCarousel({ slideWidth: SLIDE_WIDTH })
</script>

<section>
  <div id="viewport" use:carouselRef>
    <div id="track">
      {#each SLIDES as slide (slide)}
        <article>{slide}</article>
      {/each}
    </div>
  </div>

  <button id="next" on:click={() => $carousel.scrollNext()}>next</button>

  <p id="state">
    {`${$carousel.selectedIndex}/${$carousel.snapCount}/${$carousel.slidesCount}`}
  </p>
</section>
