// apps/playground-react/src/components/SelectField/index.tsx
import type { JSX } from 'react'
import { STYLES, SelectFieldProps } from '@swipi/playground-core'
import { useSelectField } from './useSelectField'

const SelectField = <Value extends string>({
  label,
  hint,
  value,
  options,
  onChange
}: SelectFieldProps<Value>): JSX.Element => {
  const { id, handleChange } = useSelectField({ onChange })

  return (
    <div className={STYLES.field} data-pg="field">
      <label className={STYLES.label} data-pg="label" htmlFor={id}>
        {label}
      </label>
      <select
        id={id}
        className={STYLES.select}
        value={value}
        onChange={handleChange}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      {hint && <span className={STYLES.hint}>{hint}</span>}
    </div>
  )
}

export default SelectField

// apps/playground-svelte/src/components/SelectField/index.svelte
<script lang="ts" generics="Value extends string">
  import { STYLES } from '@swipi/playground-core'
  import type { SelectFieldProps } from '@swipi/playground-core'

  let { label, hint, value, options, onChange }: SelectFieldProps<Value> =
    $props()

  const id = $props.id()

  const handleChange = (event: Event): void => {
    const { value: selected } = event.currentTarget as HTMLSelectElement & {
      value: Value
    }

    onChange(selected)
  }
</script>

<div class={STYLES.field} data-pg="field">
  <label class={STYLES.label} data-pg="label" for={id}>
    {label}
  </label>
  <select {id} class={STYLES.select} {value} onchange={handleChange}>
    {#each options as option (option.value)}
      <option value={option.value}>{option.label}</option>
    {/each}
  </select>
  {#if hint}
    <span class={STYLES.hint}>{hint}</span>
  {/if}
</div>
