// apps/playground-angular/src/components/Section/index.ts
import { Component, computed, input } from '@angular/core'
import type { SectionOrigin } from '@swipi/playground-core'
import { STYLES } from '@swipi/playground-core'

const BADGE: Record<SectionOrigin, string> = {
  hook: 'hook option',
  playground: 'playground only'
}

@Component({
  selector: 'pg-section',
  styles: ':host { display: contents; }',
  template: `
    <details
      [class]="STYLES.section"
      data-pg="section"
      [attr.data-origin]="origin()"
      open
    >
      <summary [class]="STYLES.sectionTitle">
        {{ title() }}
        <span [class]="STYLES.sectionBadge">{{ badge() }}</span>
      </summary>
      <div [class]="STYLES.sectionBody">
        @if (hint()) {
          <p [class]="STYLES.hint">{{ hint() }}</p>
        }
        <ng-content />
      </div>
    </details>
  `
})
export class Section {
  protected readonly STYLES = STYLES

  readonly title = input.required<string>()

  readonly origin = input.required<SectionOrigin>()

  readonly hint = input<string>()

  readonly badge = computed(() => BADGE[this.origin()])
}

// apps/playground-vue/src/components/Section/index.vue
<template>
  <details :class="STYLES.section" data-pg="section" :data-origin="origin" open>
    <summary :class="STYLES.sectionTitle">
      {{ title }}
      <span :class="STYLES.sectionBadge">{{ BADGE[origin] }}</span>
    </summary>
    <div :class="STYLES.sectionBody">
      <p v-if="hint" :class="STYLES.hint">{{ hint }}</p>
      <slot></slot>
    </div>
  </details>
</template>

<script setup lang="ts">
import { STYLES } from '@swipi/playground-core'
import type { SectionProps } from '@swipi/playground-core'

defineProps<SectionProps>()

const BADGE = {
  hook: 'hook option',
  playground: 'playground only'
} as const
</script>
