// apps/playground-svelte/src/components/TextField/index.svelte
<script lang="ts">
  import type { TextFieldProps } from '@swipi/playground-core'

  let { label, hint, value, placeholder, onChange }: TextFieldProps = $props()

  const id = $props.id()

  const handleChange = (event: Event): void => {
    onChange((event.currentTarget as HTMLInputElement).value)
  }
</script>

<div class="pg-field">
  <label class="pg-label" for={id}>
    {label}
  </label>
  <input
    {id}
    type="text"
    class="pg-input"
    {value}
    {placeholder}
    onchange={handleChange}
  />
  {#if hint}
    <span class="pg-hint">{hint}</span>
  {/if}
</div>

// apps/playground/src/components/TextField/index.tsx
import type { JSX } from 'react'
import { TextFieldProps } from '../../types'
import { useTextField } from './useTextField'

const TextField = ({
  label,
  hint,
  value,
  placeholder,
  onChange
}: TextFieldProps): JSX.Element => {
  const { id, handleChange } = useTextField({ onChange })

  return (
    <div className="pg-field">
      <label className="pg-label" htmlFor={id}>
        {label}
      </label>
      <input
        id={id}
        type="text"
        className="pg-input"
        value={value}
        placeholder={placeholder}
        onChange={handleChange}
      />
      {hint && <span className="pg-hint">{hint}</span>}
    </div>
  )
}

export default TextField
