// apps/playground-svelte/src/components/CodeBlock/index.svelte
<script lang="ts">
  import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
  import type { CodeBlockProps } from '@swipi/playground-core'

  let { code, language }: CodeBlockProps = $props()

  const tokens = $derived(highlight(code, language))
</script>

<pre class={STYLES.code}>{#each tokens as token, index (index)}<span
      class={CODE_TOKEN_STYLES[token.kind]}>{token.text}</span
    >{/each}</pre>

// apps/playground-angular/src/components/CodeBlock/index.ts
import { Component, computed, input } from '@angular/core'
import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
import type { CodeLanguage, CodeTokenKind } from '@swipi/playground-core'

@Component({
  selector: 'pg-code-block',
  styles: ':host { display: contents; }',
  template: `<pre
    [class]="STYLES.code"
  >@for (token of tokens(); track $index) {<span [class]="styleOf(token.kind)">{{ token.text }}</span>}</pre>`
})
export class CodeBlock {
  protected readonly STYLES = STYLES

  readonly code = input.required<string>()

  readonly language = input.required<CodeLanguage>()

  readonly tokens = computed(() => highlight(this.code(), this.language()))

  styleOf(kind: CodeTokenKind): string {
    return CODE_TOKEN_STYLES[kind]
  }
}
