// apps/playground-svelte/src/components/EventLog/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import type { EventLogProps } from '@swipi/playground-core'

  let { events, onClear }: EventLogProps = $props()
</script>

<div class={STYLES.card}>
  <div class={STYLES.cardHeader}>
    <h2 class={STYLES.cardTitle}>Events</h2>
    <button type="button" class={STYLES.ghostButton} onclick={onClear}>
      Clear
    </button>
  </div>
  <ul class={STYLES.events}>
    {#each events as event (event.id)}
      <li class={STYLES.event}>
        <span class={STYLES.eventName}>{event.name}</span>
        <code>{event.payload}</code>
      </li>
    {/each}
    {#if !events.length}
      <li class={STYLES.hint}>No events yet</li>
    {/if}
  </ul>
</div>

// apps/playground-react/src/components/EventLog/index.tsx
import type { JSX } from 'react'
import { STYLES, EventLogProps } from '@swipi/playground-core'

const EventLog = ({ events, onClear }: EventLogProps): JSX.Element => (
  <div className={STYLES.card}>
    <div className={STYLES.cardHeader}>
      <h2 className={STYLES.cardTitle}>Events</h2>
      <button type="button" className={STYLES.ghostButton} onClick={onClear}>
        Clear
      </button>
    </div>
    <ul className={STYLES.events}>
      {events.map((event) => (
        <li key={event.id} className={STYLES.event}>
          <span className={STYLES.eventName}>{event.name}</span>
          <code>{event.payload}</code>
        </li>
      ))}
      {!events.length && <li className={STYLES.hint}>No events yet</li>}
    </ul>
  </div>
)

export default EventLog
