// packages/react/scripts/types-fixture/app.tsx
import { useState } from 'react'
import { useSwipiCarousel } from '@midstem/swipi-react'
import type {
  SlidePositions,
  SwipiAxis,
  SwipiCarousel,
  SwipiCarouselRef,
  SwipiState
} from '@midstem/swipi-react'

const AXIS: SwipiAxis = 'y'

export const Headless = () => {
  const [carouselRef, carousel]: [SwipiCarouselRef, SwipiCarousel] =
    useSwipiCarousel({ loop: true, dragFree: true, onSelect: (state) => state })

  return (
    <>
      <div ref={carouselRef}>
        <div>
          <div>one</div>
          <div>two</div>
        </div>
      </div>

      <button onClick={carousel.scrollNext} disabled={!carousel.canScrollNext}>
        {carousel.selectedIndex} / {carousel.snapCount} / {carousel.slidesCount}
      </button>
    </>
  )
}

export const Consumer = () => {
  const [state, setState] = useState<SwipiState>()
  const [positions, setPositions] = useState<SlidePositions>()

  const [carouselRef, carousel] = useSwipiCarousel({
    axis: AXIS,
    loop: true,
    autoplay: true,
    slideWidth: 320,
    spaceBetween: 10,
    startIndex: 1,
    autoplaySpeed: 4000,
    animationSpeed: 300,
    respectReducedMotion: true,
    onSelect: setState,
    onChange: setPositions
  })

  const scrollToLast = (): void => carousel.scrollTo(carousel.snapCount - 1)

  return (
    <>
      <div ref={carouselRef}>
        <div>
          <div>one</div>
          <div>two</div>
        </div>
      </div>

      <button onClick={carousel.scrollPrev} disabled={!carousel.canScrollPrev}>
        prev
      </button>

      <button onClick={scrollToLast}>
        {state?.selectedIndex} / {state?.snapCount} / {positions?.next}
      </button>
    </>
  )
}

// packages/angular/scripts/types-fixture/app.ts
import { ElementRef, signal, type WritableSignal } from '@angular/core'
import { useSwipiCarousel } from '@midstem/swipi-angular'
import type {
  SlidePositions,
  SwipiAxis,
  SwipiCarousel,
  SwipiCarouselOptions,
  SwipiCarouselRef,
  SwipiCarouselSignal,
  SwipiCarouselSource,
  SwipiCarouselTarget,
  SwipiState
} from '@midstem/swipi-angular'

const AXIS: SwipiAxis = 'y'

export const headless = (viewport: HTMLElement): string => {
  const [carouselRef, carousel]: [SwipiCarouselRef, SwipiCarouselSignal] =
    useSwipiCarousel({
      loop: true,
      dragFree: true,
      onSelect: (state) => state
    })

  carouselRef(viewport)

  const value: SwipiCarousel = carousel()

  carouselRef(null)

  return `${value.selectedIndex} / ${value.snapCount} / ${value.slidesCount}`
}

export const consumer = (viewport: HTMLElement): (() => void) => {
  let state: SwipiState | undefined
  let positions: SlidePositions | undefined

  const options: WritableSignal<SwipiCarouselOptions> = signal({
    axis: AXIS,
    loop: true,
    autoplay: true,
    slideWidth: 320,
    spaceBetween: 10,
    startIndex: 1,
    autoplaySpeed: 4000,
    animationSpeed: 300,
    respectReducedMotion: true,
    onSelect: (next) => {
      state = next
    },
    onChange: (next) => {
      positions = next
    }
  })

  const source: SwipiCarouselSource = options

  const [carouselRef, carousel] = useSwipiCarousel(source)

  const target: SwipiCarouselTarget = new ElementRef(viewport)

  carouselRef(target)

  const value = carousel()

  if (!value.canScrollPrev) value.scrollTo(value.snapCount - 1)

  options.update((previous) => ({ ...previous, loop: false }))

  return () => {
    console.log(state?.selectedIndex, positions?.next)
    carouselRef(undefined)
  }
}
