// apps/playground-vue/src/components/Section/index.vue
<template>
  <details :class="STYLES.section" data-pg="section" :data-origin="origin" open>
    <summary :class="STYLES.sectionTitle">
      {{ title }}
      <span :class="STYLES.sectionBadge">{{ BADGE[origin] }}</span>
    </summary>
    <div :class="STYLES.sectionBody">
      <p v-if="hint" :class="STYLES.hint">{{ hint }}</p>
      <slot></slot>
    </div>
  </details>
</template>

<script setup lang="ts">
import { STYLES } from '@swipi/playground-core'
import type { SectionProps } from '@swipi/playground-core'

defineProps<SectionProps>()

const BADGE = {
  hook: 'hook option',
  playground: 'playground only'
} as const
</script>

// apps/playground-svelte/src/components/Section/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import type { SectionProps } from '../../types'

  const BADGE = {
    hook: 'hook option',
    playground: 'playground only'
  } as const

  let { title, origin, hint, children }: SectionProps = $props()
</script>

<details class={STYLES.section} data-pg="section" data-origin={origin} open>
  <summary class={STYLES.sectionTitle}>
    {title}
    <span class={STYLES.sectionBadge}>{BADGE[origin]}</span>
  </summary>
  <div class={STYLES.sectionBody}>
    {#if hint}
      <p class={STYLES.hint}>{hint}</p>
    {/if}
    {@render children()}
  </div>
</details>
