// apps/playground-svelte/src/components/NumberField/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import {
    DEFAULT_MAX,
    DEFAULT_MIN,
    DEFAULT_STEP,
    clamp
  } from '@swipi/playground-core'
  import type { NumberFieldProps } from '@swipi/playground-core'

  let {
    label,
    hint,
    value,
    min = DEFAULT_MIN,
    max = DEFAULT_MAX,
    step = DEFAULT_STEP,
    withSlider = true,
    disabled = false,
    onChange
  }: NumberFieldProps = $props()

  const id = $props.id()

  const handleChange = (event: Event): void => {
    const raw = parseFloat((event.currentTarget as HTMLInputElement).value)
    const next = Number.isNaN(raw) ? min : raw

    onChange(clamp(next, min, max))
  }
</script>

<div class={STYLES.field} data-pg="field" data-disabled={disabled}>
  <label class={STYLES.label} data-pg="label" for={id}>
    {label}
  </label>
  <div class={STYLES.fieldRow}>
    {#if withSlider}
      <input
        type="range"
        {min}
        {max}
        {step}
        {value}
        {disabled}
        onchange={handleChange}
        oninput={handleChange}
      />
    {/if}
    <input
      {id}
      type="number"
      class={STYLES.numberInput}
      {min}
      {max}
      {step}
      {value}
      {disabled}
      onchange={handleChange}
      oninput={handleChange}
    />
  </div>
  {#if hint}
    <span class={STYLES.hint}>{hint}</span>
  {/if}
</div>

// apps/playground-react/src/components/NumberField/index.tsx
import type { JSX } from 'react'
import { STYLES, NumberFieldProps } from '@swipi/playground-core'
import { DEFAULT_MAX, DEFAULT_MIN, DEFAULT_STEP } from '@swipi/playground-core'
import { useNumberField } from './useNumberField'

const NumberField = ({
  label,
  hint,
  value,
  min = DEFAULT_MIN,
  max = DEFAULT_MAX,
  step = DEFAULT_STEP,
  withSlider = true,
  disabled = false,
  onChange
}: NumberFieldProps): JSX.Element => {
  const { id, handleChange } = useNumberField({ min, max, onChange })

  return (
    <div className={STYLES.field} data-pg="field" data-disabled={disabled}>
      <label className={STYLES.label} data-pg="label" htmlFor={id}>
        {label}
      </label>
      <div className={STYLES.fieldRow}>
        {withSlider && (
          <input
            type="range"
            className={STYLES.range}
            min={min}
            max={max}
            step={step}
            value={value}
            disabled={disabled}
            onChange={handleChange}
          />
        )}
        <input
          id={id}
          type="number"
          className={STYLES.numberInput}
          min={min}
          max={max}
          step={step}
          value={value}
          disabled={disabled}
          onChange={handleChange}
        />
      </div>
      {hint && <span className={STYLES.hint}>{hint}</span>}
    </div>
  )
}

export default NumberField
