// apps/playground-react/src/components/TextField/index.tsx
import type { JSX } from 'react'
import { STYLES, TextFieldProps } from '@swipi/playground-core'
import { useTextField } from './useTextField'

const TextField = ({
  label,
  hint,
  value,
  placeholder,
  onChange
}: TextFieldProps): JSX.Element => {
  const { id, handleChange } = useTextField({ onChange })

  return (
    <div className={STYLES.field} data-pg="field">
      <label className={STYLES.label} data-pg="label" htmlFor={id}>
        {label}
      </label>
      <input
        id={id}
        type="text"
        className={STYLES.input}
        value={value}
        placeholder={placeholder}
        onChange={handleChange}
      />
      {hint && <span className={STYLES.hint}>{hint}</span>}
    </div>
  )
}

export default TextField

// apps/playground-svelte/src/components/TextField/index.svelte
<script lang="ts">
  import { STYLES } from '@swipi/playground-core'
  import type { TextFieldProps } from '@swipi/playground-core'

  let { label, hint, value, placeholder, onChange }: TextFieldProps = $props()

  const id = $props.id()

  const handleChange = (event: Event): void => {
    onChange((event.currentTarget as HTMLInputElement).value)
  }
</script>

<div class={STYLES.field} data-pg="field">
  <label class={STYLES.label} data-pg="label" for={id}>
    {label}
  </label>
  <input
    {id}
    type="text"
    class={STYLES.input}
    {value}
    {placeholder}
    onchange={handleChange}
  />
  {#if hint}
    <span class={STYLES.hint}>{hint}</span>
  {/if}
</div>
