// apps/playground-react/src/usePlayground.ts
import { useCallback, useMemo, useRef, useState } from 'react'
import { SlidePositions, SwipiState } from '@midstem/swipi-react'
import { CarouselRef } from '@swipi/playground-core'
import { DEFAULT_STATE, MAX_EVENTS, SLIDE_COLORS } from '@swipi/playground-core'
import { PlaygroundEvent, PlaygroundState } from '@swipi/playground-core'
import { UsePlaygroundReturn } from './types'

export const usePlayground = (): UsePlaygroundReturn => {
  const [state, setState] = useState<PlaygroundState>(DEFAULT_STATE)
  const [swipiState, setSwipiState] = useState<SwipiState>()
  const [positions, setPositions] = useState<SlidePositions>()
  const [events, setEvents] = useState<PlaygroundEvent[]>([])
  const [remountToken, setRemountToken] = useState<number>(0)

  const swipiRef = useRef<CarouselRef>(null)
  const eventId = useRef<number>(0)

  const update = useCallback(
    <Key extends keyof PlaygroundState>(
      key: Key,
      value: PlaygroundState[Key]
    ): void => setState((previous) => ({ ...previous, [key]: value })),
    []
  )

  const pushEvent = useCallback(
    (name: PlaygroundEvent['name'], payload: object): void => {
      eventId.current += 1

      const event: PlaygroundEvent = {
        id: eventId.current,
        name,
        payload: JSON.stringify(payload)
      }

      setEvents((previous) => [event, ...previous].slice(0, MAX_EVENTS))
    },
    []
  )

  const handleSelect = useCallback(
    (next: SwipiState): void => {
      setSwipiState(next)
      pushEvent('onSelect', next)
    },
    [pushEvent]
  )

  const handleChange = useCallback(
    (next: SlidePositions): void => {
      setPositions(next)
      pushEvent('onChange', next)
    },
    [pushEvent]
  )

  const remount = useCallback(
    (): void => setRemountToken((token) => token + 1),
    []
  )

  const clearEvents = useCallback((): void => setEvents([]), [])

  const reset = useCallback((): void => {
    setState(DEFAULT_STATE)
    setEvents([])
    remount()
  }, [remount])

  const slides = useMemo(
    () => SLIDE_COLORS.slice(0, state.slidesCount),
    [state.slidesCount]
  )

  return {
    state,
    slides,
    events,
    swipiRef,
    swipiState,
    positions,
    remountKey: `${remountToken}-${state.startIndex}`,
    update,
    remount,
    reset,
    clearEvents,
    handleSelect,
    handleChange
  }
}

// apps/playground-angular/src/usePlayground.ts
import { computed, signal } from '@angular/core'
import { SlidePositions, SwipiState } from '@midstem/swipi-angular'
import { CarouselRef } from '@swipi/playground-core'
import { DEFAULT_STATE, MAX_EVENTS, SLIDE_COLORS } from '@swipi/playground-core'
import {
  PlaygroundEvent,
  PlaygroundState,
  UpdateState
} from '@swipi/playground-core'
import { UsePlaygroundReturn } from './types'

const FIRST_EVENT_ID = 0

const NEXT_TOKEN = 1

export const usePlayground = (): UsePlaygroundReturn => {
  const state = signal<PlaygroundState>(DEFAULT_STATE)
  const swipiState = signal<SwipiState | undefined>(undefined)
  const positions = signal<SlidePositions | undefined>(undefined)
  const events = signal<PlaygroundEvent[]>([])
  const carousel = signal<CarouselRef | null>(null)
  const remountToken = signal(FIRST_EVENT_ID)

  let eventId = FIRST_EVENT_ID

  const update: UpdateState = (key, value) =>
    state.update((previous) => ({ ...previous, [key]: value }))

  const pushEvent = (name: PlaygroundEvent['name'], payload: object): void => {
    eventId += NEXT_TOKEN

    const event: PlaygroundEvent = {
      id: eventId,
      name,
      payload: JSON.stringify(payload)
    }

    events.update((previous) => [event, ...previous].slice(0, MAX_EVENTS))
  }

  const handleSelect = (next: SwipiState): void => {
    swipiState.set(next)
    pushEvent('onSelect', next)
  }

  const handleChange = (next: SlidePositions): void => {
    positions.set(next)
    pushEvent('onChange', next)
  }

  const handleReady = (next: CarouselRef): void => carousel.set(next)

  const remount = (): void => remountToken.update((token) => token + NEXT_TOKEN)

  const clearEvents = (): void => events.set([])

  const reset = (): void => {
    state.set({ ...DEFAULT_STATE })
    events.set([])
    remount()
  }

  return {
    state: state.asReadonly(),
    slides: computed(() => SLIDE_COLORS.slice(0, state().slidesCount)),
    events: events.asReadonly(),
    remountKey: computed(() => `${remountToken()}-${state().startIndex}`),
    carousel: carousel.asReadonly(),
    swipiState: swipiState.asReadonly(),
    positions: positions.asReadonly(),
    update,
    remount,
    reset,
    clearEvents,
    handleSelect,
    handleChange,
    handleReady
  }
}
