// packages/angular/src/useSwipiCarousel/__test__/carousel.ts
import { afterEach } from 'vitest'
import { ElementRef, isSignal } from '@angular/core'
import { TestBed } from '@angular/core/testing'
import { useSwipiCarousel } from '..'
import { SwipiCarousel, SwipiCarouselSource } from '../types'
import { buildSlides, SLIDE_WIDTH, SLIDES_COUNT } from './dom'

export type CarouselProps = {
  options?: SwipiCarouselSource
  count?: number
  trackStyle?: string
  asElementRef?: boolean
}

export type MountedCarousel = {
  readCarousel: () => SwipiCarousel
  readState: () => string
  setCount: (count: number) => void
  setTrackStyle: (style: string) => void
  attach: () => void
  detach: () => void
  unmount: () => void
  destroy: () => void
}

const withDefaults = (source: SwipiCarouselSource): SwipiCarouselSource =>
  isSignal(source) ? source : { slideWidth: SLIDE_WIDTH, ...source }

const readable = (carousel: SwipiCarousel): string =>
  [
    carousel.selectedIndex,
    carousel.snapCount,
    carousel.slidesCount,
    carousel.canScrollPrev,
    carousel.canScrollNext,
    carousel.hasOverflow
  ].join('/')

const live = new Set<() => void>()

afterEach(() => {
  Array.from(live).forEach((teardown) => teardown())
  TestBed.resetTestingModule()
})

export const settle = (): Promise<void> =>
  new Promise((done) => setTimeout(done, 0))

export const flush = (): void => TestBed.tick()

export const mountCarousel = (props: CarouselProps = {}): MountedCarousel => {
  const {
    options = {},
    count = SLIDES_COUNT,
    trackStyle = '',
    asElementRef = false
  } = props

  const host = document.createElement('div')
  const viewport = document.createElement('div')
  const track = document.createElement('div')

  viewport.setAttribute('data-testid', 'viewport')
  track.setAttribute('data-testid', 'track')

  if (trackStyle) track.setAttribute('style', trackStyle)

  buildSlides(track, count)
  viewport.appendChild(track)
  host.appendChild(viewport)
  document.body.appendChild(host)

  const [carouselRef, carousel] = TestBed.runInInjectionContext(() =>
    useSwipiCarousel(withDefaults(options))
  )

  const attach = (): void =>
    carouselRef(asElementRef ? new ElementRef(viewport) : viewport)

  attach()

  const teardown = (): void => {
    carouselRef(null)
    host.remove()
    live.delete(teardown)
  }

  live.add(teardown)

  return {
    readCarousel: () => carousel(),
    readState: () => readable(carousel()),
    setCount: (next: number) => buildSlides(track, next),
    setTrackStyle: (style: string) => track.setAttribute('style', style),
    attach,
    detach: () => carouselRef(null),
    unmount: teardown,
    destroy: () => TestBed.resetTestingModule()
  }
}

// packages/react/src/useSwipiCarousel/__test__/carousel.tsx
import { useState, type JSX } from 'react'
import { screen } from '@testing-library/react'
import { useSwipiCarousel } from '..'
import { SwipiCarousel, SwipiCarouselOptions } from '../types'
import { SLIDE_WIDTH, SLIDES_COUNT } from './dom'

export type CarouselProps = SwipiCarouselOptions & {
  count?: number
  onRender?: (carousel: SwipiCarousel) => void
}

export const Carousel = ({
  count = SLIDES_COUNT,
  onRender,
  ...options
}: CarouselProps): JSX.Element => {
  const [carouselRef, carousel] = useSwipiCarousel({
    slideWidth: SLIDE_WIDTH,
    ...options
  })

  onRender?.(carousel)

  return (
    <section>
      <div data-testid="viewport" ref={carouselRef}>
        <div data-testid="track">
          {Array.from({ length: count }, (_, index) => (
            <article key={index}>{index + 1}</article>
          ))}
        </div>
      </div>

      <button onClick={carousel.scrollPrev}>back</button>
      <button onClick={carousel.scrollNext}>forward</button>

      <nav>
        {Array.from({ length: carousel.snapCount }, (_, index) => (
          <button key={index} onClick={() => carousel.scrollTo(index)}>
            dot {index}
          </button>
        ))}
      </nav>

      <p data-testid="state">
        {carousel.selectedIndex}/{carousel.snapCount}/{carousel.slidesCount}/
        {String(carousel.canScrollPrev)}/{String(carousel.canScrollNext)}/
        {String(carousel.hasOverflow)}
      </p>
    </section>
  )
}

export const Host = (props: CarouselProps): JSX.Element => {
  const [, setTick] = useState(0)

  return (
    <>
      <button onClick={() => setTick((tick) => tick + 1)}>rerender</button>
      <Carousel {...props} />
    </>
  )
}

export const rerenderButton = (): HTMLElement =>
  screen.getByRole('button', { name: 'rerender' })

export const forwardButton = (): HTMLElement =>
  screen.getByRole('button', { name: 'forward' })

export const backButton = (): HTMLElement =>
  screen.getByRole('button', { name: 'back' })
