// apps/playground-angular/src/components/CodeSnippet/helpers.ts
import {
  ARROWS,
  KEYS,
  getClassNames,
  getOptions,
  isFadeInAnimation
} from '@swipi/playground-core'
import type { ClassNames, PlaygroundState } from '@swipi/playground-core'

const buildImports = (state: PlaygroundState): string => {
  const symbols = ['Component', 'effect', 'ElementRef', 'input', 'viewChild']

  if (state.showDots) symbols.splice(1, 0, 'computed')

  return `import { ${symbols.join(', ')} } from '@angular/core'`
}

const buildSelected = (state: PlaygroundState): string =>
  isFadeInAnimation(state.slidesAnimation)
    ? `
            [attr.data-selected]="index === carousel().selectedIndex"`
    : ''

const buildSlide = (state: PlaygroundState, classes: ClassNames): string => {
  const selected = buildSelected(state)

  return `        @for (item of items(); track item.id; let index = $index) {
          <div
            class="${classes.slide}"
            role="group"
            aria-roledescription="slide"
            attr.aria-label="{{ index + 1 }} of {{ items().length }}"${selected}
          >
            {{ item.title }}
          </div>
        }`
}

const buildMinimalSlide = (
  state: PlaygroundState,
  classes: ClassNames
): string => {
  const selected = buildSelected(state)

  if (!selected) {
    return `        @for (item of items(); track item.id) {
          <div class="${classes.slide}">{{ item.title }}</div>
        }`
  }

  return `        @for (item of items(); track item.id; let index = $index) {
          <div class="${classes.slide}"${selected}>
            {{ item.title }}
          </div>
        }`
}

const buildArrows = (state: PlaygroundState, minimal: boolean): string => {
  if (!state.showArrows) return ''

  const [previous, next] = ARROWS[state.axis]

  const label = (text: string): string =>
    minimal
      ? ''
      : `
        aria-label="${text}"`

  return `

      <button
        type="button"${label('Previous slide')}
        [disabled]="!carousel().canScrollPrev"
        (click)="carousel().scrollPrev()"
      >
        ${previous}
      </button>
      <button
        type="button"${label('Next slide')}
        [disabled]="!carousel().canScrollNext"
        (click)="carousel().scrollNext()"
      >
        ${next}
      </button>`
}

const buildDots = (state: PlaygroundState, minimal: boolean): string => {
  if (!state.showDots) return ''

  const marker = minimal
    ? `
          [attr.data-active]="index === carousel().selectedIndex"`
    : `
          attr.aria-label="Go to slide {{ index + 1 }}"
          [attr.aria-current]="index === carousel().selectedIndex"`

  return `

      @for (index of dots(); track index) {
        <button
          type="button"
          class="carousel__dot"${marker}
          (click)="carousel().scrollTo(index)"
        ></button>
      }`
}

const buildStatus = (classes: ClassNames): string => `

      <span class="${classes.status}" aria-live="polite" aria-atomic="true">
        Slide {{ carousel().selectedIndex + 1 }} of {{ carousel().snapCount }}
      </span>`

const buildViewport = (
  state: PlaygroundState,
  classes: ClassNames,
  minimal: boolean
): string => {
  if (minimal) {
    return `      <div #viewport class="${classes.viewport}">`
  }

  return `      <div
        #viewport
        class="${classes.viewport}"
        role="group"
        tabindex="0"
        aria-roledescription="carousel"
        aria-label="${state.ariaLabel}"
        (keydown)="handleKeyDown($event)"
      >`
}

const buildTemplate = (
  state: PlaygroundState,
  classes: ClassNames,
  minimal: boolean
): string => {
  const slides = minimal
    ? buildMinimalSlide(state, classes)
    : buildSlide(state, classes)

  const status = minimal ? '' : buildStatus(classes)

  return `${buildViewport(state, classes, minimal)}
        <div class="${classes.track}">
${slides}
        </div>
      </div>${status}${buildArrows(state, minimal)}${buildDots(state, minimal)}`
}

const buildDotsField = (state: PlaygroundState): string => {
  if (!state.showDots) return ''

  return `

  readonly dots = computed(() =>
    Array.from({ length: this.carousel().snapCount }, (_, index) => index)
  )`
}

const buildKeyboard = (state: PlaygroundState, minimal: boolean): string => {
  if (minimal) return ''

  const [previousKey, nextKey] = KEYS[state.axis]

  return `

  handleKeyDown(event: KeyboardEvent): void {
    if (event.key === '${previousKey}') this.carousel().scrollPrev()
    if (event.key === '${nextKey}') this.carousel().scrollNext()
  }`
}

export const buildMarkup = (
  state: PlaygroundState,
  minimal = false,
  tailwind = false
): string => {
  const classes = getClassNames(state, tailwind)
  const options = getOptions(state)

  return `${buildImports(state)}
import { useSwipiCarousel } from '@midstem/swipi-angular'
import type { SwipiCarouselSignal } from '@midstem/swipi-angular'

type Item = { id: string; title: string }

@Component({
  selector: 'app-carousel',
  template: \`
${buildTemplate(state, classes, minimal)}
  \`
})
export class CarouselComponent {
  readonly items = input<Item[]>([])

  readonly viewport = viewChild<ElementRef<HTMLElement>>('viewport')

  readonly carousel: SwipiCarouselSignal${buildDotsField(state)}

  constructor() {
    const [carouselRef, carousel] = useSwipiCarousel(${options})

    this.carousel = carousel

    effect(() => carouselRef(this.viewport()))
  }${buildKeyboard(state, minimal)}
}
`
}

// apps/playground-react/src/components/CodeSnippet/helpers.ts
import {
  ARROWS,
  ClassNames,
  KEYS,
  PlaygroundState,
  getClassNames,
  getOptions,
  isFadeInAnimation
} from '@swipi/playground-core'

const buildArrows = (state: PlaygroundState, minimal: boolean): string => {
  if (!state.showArrows) return ''

  const [previous, next] = ARROWS[state.axis]

  const label = (text: string): string =>
    minimal
      ? ''
      : `
        aria-label="${text}"`

  return `
      <button
        type="button"${label('Previous slide')}
        onClick={carousel.scrollPrev}
        disabled={!carousel.canScrollPrev}
      >
        ${previous}
      </button>
      <button
        type="button"${label('Next slide')}
        onClick={carousel.scrollNext}
        disabled={!carousel.canScrollNext}
      >
        ${next}
      </button>
`
}

const buildDots = (state: PlaygroundState, minimal: boolean): string => {
  if (!state.showDots) return ''

  const marker = minimal
    ? `
          data-active={index === carousel.selectedIndex}`
    : `
          aria-label={\`Go to slide \${index + 1}\`}
          aria-current={index === carousel.selectedIndex}`

  return `
      {Array.from({ length: carousel.snapCount }, (_, index) => (
        <button
          type="button"
          className="carousel__dot"
          key={index}${marker}
          onClick={() => carousel.scrollTo(index)}
        />
      ))}
`
}

const MAX_LINE_LENGTH = 80

const SLIDE_INDENT = '            '

const ATTRIBUTE_INDENT = '              '

const buildSlideTag = (className: string, selected: string): string => {
  const inline = `<div className="${className}" key={item.id}>`

  if (!selected && SLIDE_INDENT.length + inline.length <= MAX_LINE_LENGTH) {
    return inline
  }

  return [
    '<div',
    `${ATTRIBUTE_INDENT}className="${className}"`,
    `${ATTRIBUTE_INDENT}key={item.id}${selected}`,
    `${SLIDE_INDENT}>`
  ].join('\n')
}

const buildMinimalMarkup = (
  state: PlaygroundState,
  classes: ClassNames
): string => {
  const isFadeIn = isFadeInAnimation(state.slidesAnimation)

  const selected = isFadeIn
    ? `
${ATTRIBUTE_INDENT}data-selected={index === carousel.selectedIndex}`
    : ''

  const params = isFadeIn ? '(item, index)' : '(item)'

  return `import { useSwipiCarousel } from '@midstem/swipi-react'

export const Carousel = ({ items }) => {
  const [carouselRef, carousel] = useSwipiCarousel(${getOptions(state)})

  return (
    <>
      <div className="${classes.viewport}" ref={carouselRef}>
        <div className="${classes.track}">
          {items.map(${params} => (
            ${buildSlideTag(classes.slide, selected)}
              {item.title}
            </div>
          ))}
        </div>
      </div>
${buildArrows(state, true)}${buildDots(state, true)}    </>
  )
}`
}

export const buildMarkup = (
  state: PlaygroundState,
  minimal = false,
  tailwind = false
): string => {
  const classes = getClassNames(state, tailwind)

  if (minimal) return buildMinimalMarkup(state, classes)

  const selected = isFadeInAnimation(state.slidesAnimation)
    ? `
              data-selected={index === carousel.selectedIndex}`
    : ''

  const [previousKey, nextKey] = KEYS[state.axis]

  return `import { useSwipiCarousel } from '@midstem/swipi-react'

export const Carousel = ({ items }) => {
  const [carouselRef, carousel] = useSwipiCarousel(${getOptions(state)})

  const handleKeyDown = (event) => {
    if (event.key === '${previousKey}') carousel.scrollPrev()
    if (event.key === '${nextKey}') carousel.scrollNext()
  }

  return (
    <>
      <div
        className="${classes.viewport}"
        ref={carouselRef}
        role="group"
        tabIndex={0}
        aria-roledescription="carousel"
        aria-label="${state.ariaLabel}"
        onKeyDown={handleKeyDown}
      >
        <div className="${classes.track}">
          {items.map((item, index) => (
            <div
              className="${classes.slide}"
              key={item.id}
              role="group"
              aria-roledescription="slide"
              aria-label={\`\${index + 1} of \${items.length}\`}${selected}
            >
              {item.title}
            </div>
          ))}
        </div>
      </div>

      <span className="${classes.status}" aria-live="polite" aria-atomic="true">
        Slide {carousel.selectedIndex + 1} of {carousel.snapCount}
      </span>
${buildArrows(state, false)}${buildDots(state, false)}    </>
  )
}`
}
