// apps/playground/src/components/Toggle/index.tsx
import type { JSX } from 'react'
import { ToggleProps } from '../../types'
import { useToggle } from './useToggle'

const Toggle = ({
  label,
  hint,
  checked,
  disabled = false,
  onChange
}: ToggleProps): JSX.Element => {
  const { handleChange } = useToggle({ onChange })

  return (
    <label className="pg-toggle">
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={handleChange}
      />
      <span className="pg-toggle__text">
        <span className="pg-label">{label}</span>
        {hint && <span className="pg-hint">{hint}</span>}
      </span>
    </label>
  )
}

export default Toggle

// apps/playground-svelte/src/components/Toggle/index.svelte
<script lang="ts">
  import type { ToggleProps } from '@swipi/playground-core'

  let {
    label,
    hint,
    checked,
    disabled = false,
    onChange
  }: ToggleProps = $props()

  const handleChange = (event: Event): void => {
    onChange((event.currentTarget as HTMLInputElement).checked)
  }
</script>

<label class="pg-toggle">
  <input type="checkbox" {checked} {disabled} onchange={handleChange} />
  <span class="pg-toggle__text">
    <span class="pg-label">{label}</span>
    {#if hint}
      <span class="pg-hint">{hint}</span>
    {/if}
  </span>
</label>
