// apps/playground-svelte/src/components/SelectField/index.svelte
<script lang="ts" generics="Value extends string">
  import type { SelectFieldProps } from '@swipi/playground-core'

  let { label, hint, value, options, onChange }: SelectFieldProps<Value> =
    $props()

  const id = $props.id()

  const handleChange = (event: Event): void => {
    const { value: selected } = event.currentTarget as HTMLSelectElement & {
      value: Value
    }

    onChange(selected)
  }
</script>

<div class="pg-field">
  <label class="pg-label" for={id}>
    {label}
  </label>
  <select {id} class="pg-input" {value} onchange={handleChange}>
    {#each options as option (option.value)}
      <option value={option.value}>{option.label}</option>
    {/each}
  </select>
  {#if hint}
    <span class="pg-hint">{hint}</span>
  {/if}
</div>

// apps/playground/src/components/SelectField/index.tsx
import type { JSX } from 'react'
import { SelectFieldProps } from '../../types'
import { useSelectField } from './useSelectField'

const SelectField = <Value extends string>({
  label,
  hint,
  value,
  options,
  onChange
}: SelectFieldProps<Value>): JSX.Element => {
  const { id, handleChange } = useSelectField({ onChange })

  return (
    <div className="pg-field">
      <label className="pg-label" htmlFor={id}>
        {label}
      </label>
      <select
        id={id}
        className="pg-input"
        value={value}
        onChange={handleChange}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      {hint && <span className="pg-hint">{hint}</span>}
    </div>
  )
}

export default SelectField
