// apps/playground/src/components/Stage/index.tsx
import type { JSX, KeyboardEvent } from 'react'
import { useSwipiCarousel } from 'swipi'
import { StageProps } from '../../types'
import { useStage } from './useStage'
import {
  getArrows,
  getSlideStyle,
  getTrackStyle,
  getViewportStyle,
  isNextKey,
  isPreviousKey
} from './helpers'

const Stage = ({
  state,
  slides,
  swipiRef,
  onSelect,
  onChange
}: StageProps): JSX.Element => {
  const {
    bias,
    isVertical,
    slideWidth,
    spaceBetween,
    visibleSlides,
    windowWidth,
    activeBreakpoint
  } = useStage({ state })

  const [carouselRef, carousel] = useSwipiCarousel({
    axis: state.axis,
    loop: state.loop,
    dragFree: state.dragFree,
    autoplay: state.autoplay,
    startIndex: state.startIndex,
    autoplaySpeed: state.autoplaySpeed,
    animationSpeed: state.animationSpeed,
    respectReducedMotion: state.respectReducedMotion,
    slideWidth,
    spaceBetween,
    onSelect,
    onChange
  })

  swipiRef.current = {
    scrollNext: carousel.scrollNext,
    scrollPrev: carousel.scrollPrev,
    scrollTo: carousel.scrollTo,
    selectedScrollSnap: () => carousel.selectedIndex,
    scrollSnapList: () =>
      Array.from({ length: carousel.snapCount }, (_, index) => index),
    canScrollNext: () => carousel.canScrollNext,
    canScrollPrev: () => carousel.canScrollPrev
  }

  const showArrows = state.showArrows && carousel.hasOverflow

  const [previousArrow, nextArrow] = getArrows(isVertical)

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>): void => {
    if (isPreviousKey(event.key, isVertical)) carousel.scrollPrev()
    if (isNextKey(event.key, isVertical)) carousel.scrollNext()
  }

  return (
    <div className="pg-card">
      <div className="pg-stage__slider" style={{ width: state.stageWidth }}>
        <div
          className={`pg-carousel${isVertical ? ' pg-carousel--vertical' : ''}`}
        >
          <span className="pg-visually-hidden" aria-live="polite" aria-atomic>
            Slide {carousel.selectedIndex + 1} of {carousel.snapCount}
          </span>

          <div className="pg-carousel__row">
            {showArrows && (
              <button
                type="button"
                className="pg-carousel__arrow"
                aria-label="Previous slide"
                disabled={!carousel.canScrollPrev}
                onClick={carousel.scrollPrev}
              >
                {previousArrow}
              </button>
            )}

            <div
              ref={carouselRef}
              className="pg-carousel__viewport"
              style={getViewportStyle(state, isVertical)}
              role="group"
              tabIndex={0}
              aria-roledescription="carousel"
              aria-label={state.ariaLabel}
              onKeyDown={handleKeyDown}
            >
              <div
                className="pg-carousel__track"
                style={getTrackStyle(visibleSlides, bias, slideWidth)}
              >
                {slides.map((color, index) => (
                  <div
                    key={color}
                    className="pg-carousel__slide"
                    role="group"
                    aria-roledescription="slide"
                    aria-label={`${index + 1} of ${slides.length}`}
                    style={getSlideStyle(
                      state,
                      index === carousel.selectedIndex
                    )}
                  >
                    <div
                      className="pg-carousel__slide-box"
                      style={{ backgroundColor: color }}
                    >
                      {index + 1}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {showArrows && (
              <button
                type="button"
                className="pg-carousel__arrow"
                aria-label="Next slide"
                disabled={!carousel.canScrollNext}
                onClick={carousel.scrollNext}
              >
                {nextArrow}
              </button>
            )}
          </div>

          {state.showDots && (
            <nav className="pg-carousel__dots">
              {Array.from({ length: carousel.snapCount }, (_, index) => {
                const isActive = index === carousel.selectedIndex

                return (
                  <button
                    key={index}
                    type="button"
                    className="pg-carousel__dot"
                    aria-label={`Go to slide ${index + 1}`}
                    aria-current={isActive}
                    onClick={() => carousel.scrollTo(index)}
                  >
                    <span
                      className="pg-carousel__dot-mark"
                      data-active={isActive}
                      style={{ transition: `${state.animationSpeed}ms` }}
                    />
                  </button>
                )
              })}
            </nav>
          )}
        </div>
      </div>

      <ul className="pg-facts">
        <li>
          window width: <b>{windowWidth}px</b>
        </li>
        <li>
          visible slides: <b>{visibleSlides}</b>
        </li>
        <li>
          snap positions: <b>{carousel.snapCount}</b>
        </li>
        <li>
          active breakpoint:{' '}
          <b>
            {activeBreakpoint
              ? `maxWidth ${activeBreakpoint.maxWidth}`
              : 'none'}
          </b>
        </li>
      </ul>

      {!carousel.hasOverflow && (
        <p className="pg-warning">
          All slides fit on the screen, so arrows, dots navigation and{' '}
          <code>loop</code> are disabled — add more slides, decrease{' '}
          <code>slidesNumber</code> or narrow the stage.
        </p>
      )}
    </div>
  )
}

export default Stage

// apps/playground-vue/src/components/Stage/index.vue
<template>
  <div class="pg-card">
    <div class="pg-stage__slider" :style="{ width: state.stageWidth + 'px' }">
      <div :class="['pg-carousel', { 'pg-carousel--vertical': isVertical }]">
        <span class="pg-visually-hidden" aria-live="polite" aria-atomic="true">
          Slide {{ carousel.selectedIndex + 1 }} of {{ carousel.snapCount }}
        </span>

        <div class="pg-carousel__row">
          <button
            v-if="showArrows"
            type="button"
            class="pg-carousel__arrow"
            aria-label="Previous slide"
            :disabled="!carousel.canScrollPrev"
            @click="carousel.scrollPrev()"
          >
            {{ previousArrow }}
          </button>

          <div
            :ref="carouselRef"
            class="pg-carousel__viewport"
            :style="getViewportStyle(state, isVertical)"
            role="group"
            tabindex="0"
            aria-roledescription="carousel"
            :aria-label="state.ariaLabel"
            @keydown="handleKeyDown"
          >
            <div
              class="pg-carousel__track"
              :style="getTrackStyle(visibleSlides, bias, slideWidth)"
            >
              <div
                v-for="(color, index) in slides"
                :key="color"
                class="pg-carousel__slide"
                role="group"
                aria-roledescription="slide"
                :aria-label="`${index + 1} of ${slides.length}`"
                :style="getSlideStyle(state, index === carousel.selectedIndex)"
              >
                <div
                  class="pg-carousel__slide-box"
                  :style="{ backgroundColor: color }"
                >
                  {{ index + 1 }}
                </div>
              </div>
            </div>
          </div>

          <button
            v-if="showArrows"
            type="button"
            class="pg-carousel__arrow"
            aria-label="Next slide"
            :disabled="!carousel.canScrollNext"
            @click="carousel.scrollNext()"
          >
            {{ nextArrow }}
          </button>
        </div>

        <nav v-if="state.showDots" class="pg-carousel__dots">
          <button
            v-for="(_, index) in carousel.snapCount"
            :key="index"
            type="button"
            class="pg-carousel__dot"
            :aria-label="`Go to slide ${index + 1}`"
            :aria-current="index === carousel.selectedIndex"
            @click="carousel.scrollTo(index)"
          >
            <span
              class="pg-carousel__dot-mark"
              :data-active="index === carousel.selectedIndex"
              :style="{ transition: `${state.animationSpeed}ms` }"
            />
          </button>
        </nav>
      </div>
    </div>

    <ul class="pg-facts">
      <li>
        window width: <b>{{ windowWidth }}px</b>
      </li>
      <li>
        visible slides: <b>{{ visibleSlides }}</b>
      </li>
      <li>
        snap positions: <b>{{ carousel.snapCount }}</b>
      </li>
      <li>
        active breakpoint:
        <b>{{
          activeBreakpoint ? `maxWidth ${activeBreakpoint.maxWidth}` : 'none'
        }}</b>
      </li>
    </ul>

    <p v-if="!carousel.hasOverflow" class="pg-warning">
      All slides fit on the screen, so arrows, dots navigation and
      <code>loop</code> are disabled — add more slides, decrease
      <code>slidesNumber</code> or narrow the stage.
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useSwipiCarousel } from 'swipi-vue'
import type { SlidePositions, SwipiState } from 'swipi-vue'
import {
  VERTICAL_AXIS,
  getActiveBreakpoint,
  getArrows,
  getBias,
  getConfig,
  getSlideStyle,
  getSlideWidth,
  getSpaceBetween,
  getTrackStyle,
  getViewportStyle,
  getVisibleSlides,
  isNextKey,
  isPreviousKey
} from '@swipi/playground-core'
import type { CarouselRef } from '@swipi/playground-core'
import type { StageProps } from '../../types'

const props = defineProps<StageProps>()

const emit = defineEmits<{
  (e: 'select', state: SwipiState): void
  (e: 'change', positions: SlidePositions): void
  (e: 'ready', carousel: CarouselRef): void
}>()

const windowWidth = ref(window.innerWidth)

const onResize = (): void => {
  windowWidth.value = window.innerWidth
}

onMounted(() => window.addEventListener('resize', onResize))

onUnmounted(() => window.removeEventListener('resize', onResize))

const config = computed(() => getConfig(props.state))

const activeBreakpoint = computed(() =>
  getActiveBreakpoint(config.value, windowWidth.value)
)

const isVertical = computed(() => props.state.axis === VERTICAL_AXIS)

const visibleSlides = computed(() =>
  getVisibleSlides(props.state, config.value, windowWidth.value)
)

const bias = computed(() =>
  getBias(props.state, config.value, windowWidth.value, visibleSlides.value)
)

const slideWidth = computed(() => getSlideWidth(props.state))

const spaceBetween = computed(() =>
  getSpaceBetween(props.state, config.value, windowWidth.value)
)

const [carouselRef, carousel] = useSwipiCarousel(
  computed(() => ({
    axis: props.state.axis,
    loop: props.state.loop,
    dragFree: props.state.dragFree,
    autoplay: props.state.autoplay,
    startIndex: props.state.startIndex,
    autoplaySpeed: props.state.autoplaySpeed,
    animationSpeed: props.state.animationSpeed,
    respectReducedMotion: props.state.respectReducedMotion,
    slideWidth: slideWidth.value,
    spaceBetween: spaceBetween.value,
    onSelect: (state: SwipiState) => emit('select', state),
    onChange: (positions: SlidePositions) => emit('change', positions)
  }))
)

onMounted(() => {
  emit('ready', {
    scrollNext: carousel.scrollNext,
    scrollPrev: carousel.scrollPrev,
    scrollTo: carousel.scrollTo,
    selectedScrollSnap: () => carousel.selectedIndex,
    scrollSnapList: () =>
      Array.from({ length: carousel.snapCount }, (_, index) => index),
    canScrollNext: () => carousel.canScrollNext,
    canScrollPrev: () => carousel.canScrollPrev
  })
})

const showArrows = computed(
  () => props.state.showArrows && carousel.hasOverflow
)

const previousArrow = computed(() => getArrows(isVertical.value)[0])

const nextArrow = computed(() => getArrows(isVertical.value)[1])

const handleKeyDown = (event: KeyboardEvent): void => {
  if (isPreviousKey(event.key, isVertical.value)) carousel.scrollPrev()
  if (isNextKey(event.key, isVertical.value)) carousel.scrollNext()
}
</script>
