// apps/playground-vue/src/components/CodeBlock/index.vue
<template>
  <pre :class="STYLES.code"><span
      v-for="(token, index) in tokens"
      :key="index"
      :class="CODE_TOKEN_STYLES[token.kind]"
    >{{ token.text }}</span></pre>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
import type { CodeBlockProps } from '@swipi/playground-core'

const props = defineProps<CodeBlockProps>()

const tokens = computed(() => highlight(props.code, props.language))
</script>

// apps/playground-svelte/src/components/CodeBlock/index.svelte
<script lang="ts">
  import { CODE_TOKEN_STYLES, STYLES, highlight } from '@swipi/playground-core'
  import type { CodeBlockProps } from '@swipi/playground-core'

  let { code, language }: CodeBlockProps = $props()

  const tokens = $derived(highlight(code, language))
</script>

<pre class={STYLES.code}>{#each tokens as token, index (index)}<span
      class={CODE_TOKEN_STYLES[token.kind]}>{token.text}</span
    >{/each}</pre>
